/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-05-16 09:19:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fireProposal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Code/InsuranceSystem/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/InsuranceSystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1614745664078L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>보험상품 개발</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   function duplicationInsuranceName() {\r\n");
      out.write("      //보험상품 이름의 중복확인\r\n");
      out.write("      \tvar propForm = document.getElementById('fireProposal')\r\n");
      out.write("\t\tpropForm.action = \"duplicationProposalName\"\r\n");
      out.write("\t\tpropForm.submit()\r\n");
      out.write("   }\r\n");
      out.write("   function tempSave() {\r\n");
      out.write("      alert('임시저장되었습니다.');\r\n");
      out.write("      var propForm = document.getElementById('fireProposal') // .submit();\r\n");
      out.write("      propForm.action = \"tempSave\"\r\n");
      out.write("      propForm.submit()\r\n");
      out.write("   }\r\n");
      out.write("   function submitProposal() {\r\n");
      out.write("      alert('제안서 작성이 완료되었습니다.');\r\n");
      out.write("      var propForm = document.getElementById('fireProposal') // .submit();\r\n");
      out.write("      propForm.action = \"writeProposal\"\r\n");
      out.write("      propForm.submit()\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <!--       보험상품 이름입력, 가입업종, 화재시설, 보험가입금액, 예정위험률, 화재설비 할인율, 보험료 란  -->\r\n");
      out.write("   <form action=\"writeFireProposal\" id=\"fireProposal\" method=\"post\">\r\n");
      out.write("      <table>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("               <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n");
      out.write("                  <tr style=\"background: url('img/table_mid.gif') repeat-x; text-align: center;\">\r\n");
      out.write("                     <td width=\"5\">\r\n");
      out.write("                        <img src=\"img/table_left.gif\" width=\"5\" height=\"30\" />\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>화재보험 제안서</td>\r\n");
      out.write("                     <td width=\"5\">\r\n");
      out.write("                        <img src=\"img/table_right.gif\" width=\"5\" height=\"30\" />\r\n");
      out.write("                     </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </table>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("               <table>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">제안서 이름</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"proposalName\" size=\"50\" maxlength=\"100\"> \r\n");
      out.write("                        <!-- <input type=\"button\" value=\"중복확인\" onclick=\"duplicationInsuranceName()\"> <input type=\"hidden\" name=\"insuranceNameDuplication\" value=\"nameUncheck\"> -->\r\n");
      out.write("                     </td>\r\n");
      out.write("\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">주택설비에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"housingRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                   <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">주류설비에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"pubRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                   <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">레스토랑 설비에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"restaurantRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                   <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">스포츠시설에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"sportFacilityRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                   <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">PC시설에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"PCRoomRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                   <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">수영장 시설에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"swimmingPoolRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                   <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">조사시설에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"researchFacilityRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                   <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">산업시설에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"industryFacilityRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                   <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">농업시설에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"agriculturalFacilityRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                   <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">화학시설에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"chemistryFacilityRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                   <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">나무재질에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"woodenHouseRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                   <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">한옥재질에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"koreanHouseRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">서양가옥재질에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"westernHouseRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">화재방지시설에 대한 할인율</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"firePreventionFacilityRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">비닐 재질에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=vinylHouseRate size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">서류</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input type=file name=\"verificationDocuments\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">기타사항</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"proposalContent\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#82B5DF\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr align=\"center\">\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td colspan=\"2\">\r\n");
      out.write("                        <input type = \"hidden\" name =\"whichProposal\" value=\"fire\">\r\n");
      out.write("                       <!-- <button onclick=\"javascript:tempSave()\">임시저장</button> --> \r\n");
      out.write("                        <button onclick=\"javascript:submitProposal()\">제안서 제출</button>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </table>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("   </form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
