/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-05-09 08:38:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Code/InsuranceSystem/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/InsuranceSystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1614745664078L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <!-- Theme Made By www.w3schools.com -->\r\n");
      out.write("  <title>MJU Insurance</title>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Lato\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("  body {\r\n");
      out.write("    font: 400 15px Lato, sans-serif;\r\n");
      out.write("    line-height: 1.8;\r\n");
      out.write("    color: #818181;\r\n");
      out.write("  }\r\n");
      out.write("  h2 {\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    color: #303030;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("  }\r\n");
      out.write("  h4 {\r\n");
      out.write("    font-size: 19px;\r\n");
      out.write("    line-height: 1.375em;\r\n");
      out.write("    color: #303030;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("  }  \r\n");
      out.write("  .jumbotron {\r\n");
      out.write("    background-color: #119154;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    padding: 100px 25px;\r\n");
      out.write("    font-family: Montserrat, sans-serif;\r\n");
      out.write("  }\r\n");
      out.write("  .container-fluid {\r\n");
      out.write("    padding: 60px 50px;\r\n");
      out.write("  }\r\n");
      out.write("  .bg-grey {\r\n");
      out.write("    background-color: #f6f6f6;\r\n");
      out.write("  }\r\n");
      out.write("  .logo-small {\r\n");
      out.write("    color: #119154;\r\n");
      out.write("    font-size: 50px;\r\n");
      out.write("  }\r\n");
      out.write("  .logo {\r\n");
      out.write("    color: #119154;\r\n");
      out.write("    font-size: 200px;\r\n");
      out.write("  }\r\n");
      out.write("  .thumbnail {\r\n");
      out.write("    padding: 0 0 15px 0;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 0;\r\n");
      out.write("  }\r\n");
      out.write("  .thumbnail img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("  }\r\n");
      out.write("  .carousel-control.right, .carousel-control.left {\r\n");
      out.write("    background-image: none;\r\n");
      out.write("    color: #119154;\r\n");
      out.write("  }\r\n");
      out.write("  .carousel-indicators li {\r\n");
      out.write("    border-color: #119154;\r\n");
      out.write("  }\r\n");
      out.write("  .carousel-indicators li.active {\r\n");
      out.write("    background-color: #119154;\r\n");
      out.write("  }\r\n");
      out.write("  .item h4 {\r\n");
      out.write("    font-size: 19px;\r\n");
      out.write("    line-height: 1.375em;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("    margin: 70px 0;\r\n");
      out.write("  }\r\n");
      out.write("  .item span {\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("  }\r\n");
      out.write("  .panel {\r\n");
      out.write("    border: 1px solid #119154; \r\n");
      out.write("    border-radius:0 !important;\r\n");
      out.write("    transition: box-shadow 0.5s;\r\n");
      out.write("  }\r\n");
      out.write("  .panel:hover {\r\n");
      out.write("    box-shadow: 5px 0px 40px rgba(0,0,0, .2);\r\n");
      out.write("  }\r\n");
      out.write("  .panel-footer .btn:hover {\r\n");
      out.write("    border: 1px solid #119154;\r\n");
      out.write("    background-color: #fff !important;\r\n");
      out.write("    color: #119154;\r\n");
      out.write("  }\r\n");
      out.write("  .panel-heading {\r\n");
      out.write("    color: #fff !important;\r\n");
      out.write("    background-color: #119154 !important;\r\n");
      out.write("    padding: 25px;\r\n");
      out.write("    border-bottom: 1px solid transparent;\r\n");
      out.write("    border-top-left-radius: 0px;\r\n");
      out.write("    border-top-right-radius: 0px;\r\n");
      out.write("    border-bottom-left-radius: 0px;\r\n");
      out.write("    border-bottom-right-radius: 0px;\r\n");
      out.write("  }\r\n");
      out.write("  .panel-footer {\r\n");
      out.write("    background-color: white !important;\r\n");
      out.write("  }\r\n");
      out.write("  .panel-footer h3 {\r\n");
      out.write("    font-size: 32px;\r\n");
      out.write("  }\r\n");
      out.write("  .panel-footer h4 {\r\n");
      out.write("    color: #aaa;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("  }\r\n");
      out.write("  .panel-footer .btn {\r\n");
      out.write("    margin: 15px 0;\r\n");
      out.write("    background-color: #119154;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar {\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("    background-color: #119154;\r\n");
      out.write("    z-index: 9999;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    font-size: 12px !important;\r\n");
      out.write("    line-height: 1.42857143 !important;\r\n");
      out.write("    letter-spacing: 4px;\r\n");
      out.write("    border-radius: 0;\r\n");
      out.write("    font-family: Montserrat, sans-serif;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar li a, .navbar .navbar-brand {\r\n");
      out.write("    color: #fff !important;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-nav li a:hover, .navbar-nav li.active a {\r\n");
      out.write("    color: #119154 !important;\r\n");
      out.write("    background-color: #fff !important;\r\n");
      out.write("  }\r\n");
      out.write("  .navbar-default .navbar-toggle {\r\n");
      out.write("    border-color: transparent;\r\n");
      out.write("    color: #fff !important;\r\n");
      out.write("  }\r\n");
      out.write("  footer .glyphicon {\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    color: #119154;\r\n");
      out.write("  }\r\n");
      out.write("  .slideanim {visibility:hidden;}\r\n");
      out.write("  .slide {\r\n");
      out.write("    animation-name: slide;\r\n");
      out.write("    -webkit-animation-name: slide;\r\n");
      out.write("    animation-duration: 1s;\r\n");
      out.write("    -webkit-animation-duration: 1s;\r\n");
      out.write("    visibility: visible;\r\n");
      out.write("  }\r\n");
      out.write("  @keyframes slide {\r\n");
      out.write("    0% {\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      transform: translateY(70%);\r\n");
      out.write("    } \r\n");
      out.write("    100% {\r\n");
      out.write("      opacity: 1;\r\n");
      out.write("      transform: translateY(0%);\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  @-webkit-keyframes slide {\r\n");
      out.write("    0% {\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      -webkit-transform: translateY(70%);\r\n");
      out.write("    } \r\n");
      out.write("    100% {\r\n");
      out.write("      opacity: 1;\r\n");
      out.write("      -webkit-transform: translateY(0%);\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  @media screen and (max-width: 768px) {\r\n");
      out.write("    .col-sm-4 {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin: 25px 0;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-lg {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      margin-bottom: 35px;\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  @media screen and (max-width: 480px) {\r\n");
      out.write("    .logo {\r\n");
      out.write("      font-size: 150px;\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"myPage\" data-spy=\"scroll\" data-target=\".navbar\" data-offset=\"60\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#myPage\">MJU</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        <li><a href=\"#about\">ABOUT</a></li>\r\n");
      out.write("        <li><a href=\"#customer\">CUSTOMER</a></li>\r\n");
      out.write("        <li><a href=\"#salesman\">SALESMAN</a></li>\r\n");
      out.write("        <li><a href=\"#insuranceInteralApprover\">InternalApprover</a></li>\r\n");
      out.write("        <li><a href=\"#developer\">DEVELOPER</a></li>\r\n");
      out.write("        \r\n");
      out.write("        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"jumbotron text-center\">\r\n");
      out.write("  <h1>MJU Insurance Company</h1> \r\n");
      out.write("  <p>언제나 당신의 뒤에서 당신을 지켜드립니다</p> \r\n");
      out.write("  <form class=\"form-inline\">\r\n");
      out.write("    <div class=\"input-group\">\r\n");
      out.write("      <input type=\"email\" class=\"form-control\" size=\"50\" placeholder=\"Email Address\" required>\r\n");
      out.write("      <div class=\"input-group-btn\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-success\">Subscribe</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Container (About Section) -->\r\n");
      out.write("<div id=\"about\" class=\"container-fluid\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t<h2>MJU 보험사</h2>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t다이렉트 운전자보험 가입 고객 25만 누적은 20년 4월 기준입니다.<br> 저렴한 보험료, 보험료 할인은\r\n");
      out.write("\t\t\t\t\t자동차보험 가입/유지 고객님께만 드리는 혜택입니다. <br>\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t암보험은 15년/20년 만기 자동갱신형, 유병력자 건강보험은 80세/90세/100세 만기 비갱신형, 실손보험은 1년 단위\r\n");
      out.write("\t\t\t\t\t갱신(전 보험사 공통) 15년 만기 재가입형이며, 유병력자 실손보험은 1년 단위 갱신 3년 만기 재가입형이며, 갱신 시\r\n");
      out.write("\t\t\t\t\t보험료가 인상될 수 있습니다. 모든 담보는 해당 특약 가입 시 보상됩니다.<br> - 보험가입금액 1억원 이상\r\n");
      out.write("\t\t\t\t\t~ 2억원 미만(다만, 1억 9,700만원 초과 2억원 미만은 가입대상에서 제외) : 주계약 영업보험료의 3.0% -\r\n");
      out.write("\t\t\t\t\t보험가입금액 2억원 : 주계약 영업보험료의 4.0% - 주계약 영업보험료는 해당 상품 보험료 중 특약 외 주계약으로만\r\n");
      out.write("\t\t\t\t\t납입되는 보험료를 의미합니다\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-default btn-lg\">Get in Touch</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-signal logo\"></span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid bg-grey\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<span class=\"glyphicon glyphicon-globe logo slideanim\"></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t<h2>MJU's Values</h2>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t<strong>MISSION</strong> <br>2001년 대한민국 최초로 다이렉트 자동차보험을 선보인 이래로, 대한민국\r\n");
      out.write("\t\t\t\t\t보험시장의 혁신을 선도하는 최고의 다이렉트 보험사로 자리 매김하고 있습니다.\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<strong>VISION</strong> <br>고객중심의 생각과 혁신을 바탕으로 업계 최초 1:1 보상상담서비스를\r\n");
      out.write("\t\t\t\t\t도입하였고, 국내 최초로 마일리지 자동차보험, 모바일을 통한 차별화된 보상서비스를 출시하는 등 고객의 요구에 맞는 다양한\r\n");
      out.write("\t\t\t\t\t상품과 서비스를 지속적으로 제공하고 있습니다. 더불어 운전자보험, 치아보험, 입원비보험 등 상해, 장기보험으로까지\r\n");
      out.write("\t\t\t\t\t사업영역을 성공적으로 확장하여 종합손해보험사로서 도약해나가고 있습니다.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Container (customer Section) -->\r\n");
      out.write("<div id=\"customer\" class=\"container-fluid text-center\">\r\n");
      out.write("  <h2>CUSTOMER</h2>\r\n");
      out.write("  <h4>고객 서비스</h4>\r\n");
      out.write("  <br>\r\n");
      out.write("  <div class=\"row slideanim\">\r\n");
      out.write("    <div class=\"col-sm-4\"><a href=\"#\" onclick=\"showAllInsurance()\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-search logo-small\"></span>\r\n");
      out.write("      <h4>SEARCH</h4>\r\n");
      out.write("      <p>보험상품 조회하기</p>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\"><a href=\"#\" onclick=\"allContract()\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-check logo-small\"></span>\r\n");
      out.write("      <h4>CONTRACT</h4>\r\n");
      out.write("      <p>계약확인하기</p>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-lock logo-small\"></span>\r\n");
      out.write("      <h4>JOB DONE</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <div class=\"row slideanim\">\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-leaf logo-small\"></span>\r\n");
      out.write("      <h4>GREEN</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-certificate logo-small\"></span>\r\n");
      out.write("      <h4>CERTIFIED</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-wrench logo-small\"></span>\r\n");
      out.write("      <h4 style=\"color:#303030;\">HARD WORK</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Container (salesman Section) -->\r\n");
      out.write("<div id=\"salesman\" class=\"container-fluid text-center bg-grey\">\r\n");
      out.write("  <h2>SALESMAN</h2><br>\r\n");
      out.write("  <h4>영업사원 메뉴</h4>\r\n");
      out.write("  <br>\r\n");
      out.write("  <div class=\"row slideanim\">\r\n");
      out.write("    <div class=\"col-sm-4\"><a href=\"#\" onclick=\"joinInsurance()\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-log-in logo-small\"></span>\r\n");
      out.write("      <h4>SALES</h4>\r\n");
      out.write("      <p>보험상품 영업하기 (가입시키기)</p>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\"><a href=\"#\" onclick=\"showCustomerForSales()\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-list logo-small\"></span>\r\n");
      out.write("      <h4>showCustomerForSales</h4>\r\n");
      out.write("      <p>영업고객 조회하기</p>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-lock logo-small\"></span>\r\n");
      out.write("      <h4>JOB DONE</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <div class=\"row slideanim\">\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-leaf logo-small\"></span>\r\n");
      out.write("      <h4>GREEN</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-certificate logo-small\"></span>\r\n");
      out.write("      <h4>CERTIFIED</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-wrench logo-small\"></span>\r\n");
      out.write("      <h4 style=\"color:#303030;\">HARD WORK</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<!-- Container (insuranceInteralApprover Section) -->\r\n");
      out.write("<div id=\"insuranceInteralApprover\" class=\"container-fluid text-center\">\r\n");
      out.write("    <h2>InternalApprover</h2>\r\n");
      out.write("    <h4>내부승인자</h4>\r\n");
      out.write("  <br>\r\n");
      out.write("  <div class=\"row slideanim\">\r\n");
      out.write("    <div class=\"col-sm-4\"><a href=\"#\" onclick=\"approveInternal()\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-export logo-small\"></span>\r\n");
      out.write("      <h4>approveInternal</h4>\r\n");
      out.write("      <p>제안서 내부승인하기(외부승인요청하기)</p>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\"><a href=\"#\" onclick=\"approveExternal()\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-thumbs-up logo-small\"></span>\r\n");
      out.write("      <h4>approveExternal</h4>\r\n");
      out.write("      <p>제안서 외부승인하기</p>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\"><a href=\"#\" onclick=\"makeInsurancePublicFromProposal()\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-saved logo-small\"></span>\r\n");
      out.write("      <h4>PublicFromProposal</h4>\r\n");
      out.write("      <p>제안서 공시하기</p>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <div class=\"row slideanim\">\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-leaf logo-small\"></span>\r\n");
      out.write("      <h4>GREEN</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-certificate logo-small\"></span>\r\n");
      out.write("      <h4>CERTIFIED</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-wrench logo-small\"></span>\r\n");
      out.write("      <h4 style=\"color:#303030;\">HARD WORK</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Container (developer Section) -->\r\n");
      out.write("<div id=\"developer\" class=\"container-fluid text-center bg-grey\">\r\n");
      out.write("  <h2 class=\"text-center\">DEVELOPER</h2>\r\n");
      out.write("  <h4>보험 개발자</h4>\r\n");
      out.write("  <br>\r\n");
      out.write("  <div class=\"row slideanim\">\r\n");
      out.write("    <div class=\"col-sm-4\"><a href=\"#\" onclick=\"pageChange()\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-pencil logo-small\"></span>\r\n");
      out.write("      <h4>DevelopProposal</h4>\r\n");
      out.write("      <p>제안서 개발하기</p>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\"><a href=\"#\" onclick=\"requestInternalApprover()\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-export logo-small\"></span>\r\n");
      out.write("      <h4>RequestInternalApprover</h4>\r\n");
      out.write("      <p>제안서 내부승인 요청하기</p>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-lock logo-small\"></span>\r\n");
      out.write("      <h4>JOB DONE</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <div class=\"row slideanim\">\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-leaf logo-small\"></span>\r\n");
      out.write("      <h4>GREEN</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-certificate logo-small\"></span>\r\n");
      out.write("      <h4>CERTIFIED</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-4\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-wrench logo-small\"></span>\r\n");
      out.write("      <h4 style=\"color:#303030;\">HARD WORK</h4>\r\n");
      out.write("      <p>Lorem ipsum dolor sit amet..</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"container-fluid text-center\">\r\n");
      out.write("  <a href=\"#myPage\" title=\"To Top\">\r\n");
      out.write("    <span class=\"glyphicon glyphicon-chevron-up\"></span>\r\n");
      out.write("  </a>\r\n");
      out.write("  <p>Made By MJU Insurance Company</p>\r\n");
      out.write("</footer>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");

	String currentLogin = "";
	if(session.getAttribute("customer") != null){
		currentLogin = "customer";
	}else if(session.getAttribute("salesman") != null){
		currentLogin = "salesman";
	}else if(session.getAttribute("insuranceInteralApprover") != null){
		currentLogin = "insuranceInteralApprover";
	}else if(session.getAttribute("insuranceDeveloper") != null){
		currentLogin = "insuranceDeveloper";
	}
	System.out.println("현재 로그인 : " + currentLogin);

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction pageChange() {\r\n");
      out.write("\t\tif(");
      out.print( currentLogin.equals("insuranceDeveloper") );
      out.write("){\r\n");
      out.write("\t\t\tlocation.href = \"proposalRequest\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"보험 개발자로 로그인하세요!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction requestInternalApprover() {\r\n");
      out.write("\t\tif(");
      out.print( currentLogin.equals("insuranceDeveloper") );
      out.write("){\r\n");
      out.write("\t\t\tlocation.href = \"beforeInternalApproved\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"보험 개발자로 로그인하세요!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction approveInternal() {\r\n");
      out.write("\t\tif(");
      out.print( currentLogin.equals("insuranceInteralApprover") );
      out.write("){\r\n");
      out.write("\t\t\tlocation.href = \"afterInternalApproved\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"보험 내부 승인자로 로그인하세요!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction approveExternal() {\r\n");
      out.write("\t\tif(");
      out.print( currentLogin.equals("insuranceInteralApprover") );
      out.write("){\r\n");
      out.write("\t\t\tlocation.href = \"afterExternalApproved\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"보험 내부 승인자로 로그인하세요!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction makeInsurancePublicFromProposal() {\r\n");
      out.write("\t\tif(");
      out.print( currentLogin.equals("insuranceInteralApprover") );
      out.write("){\r\n");
      out.write("\t\t\tlocation.href = \"makeInsurancePublicFromProposal\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"보험 내부 승인자로 로그인하세요!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction showAllInsurance() {\r\n");
      out.write("\t\tlocation.href = \"allInsurance\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction joinInsurance(){\r\n");
      out.write("\t\tif(");
      out.print( currentLogin.equals("salesman") );
      out.write("){\r\n");
      out.write("\t\t\tlocation.href = \"insuranceList\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"영업사원으로 로그인하세요!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction showCustomerForSales(){\r\n");
      out.write("\t\tif(");
      out.print( currentLogin.equals("salesman") );
      out.write("){\r\n");
      out.write("\t\t\tlocation.href = \"showCustomerForSales\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"영업사원으로 로그인하세요!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction allContract(){\r\n");
      out.write("\t\tif(");
      out.print( currentLogin.equals("customer") );
      out.write("){\r\n");
      out.write("\t\t\tlocation.href = \"allContract\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"고객으로 로그인하세요!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction login(){\r\n");
      out.write("\t\tlocation.href = \"login\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction logout(){\r\n");
      out.write("\t\tlocation.href = \"logout\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction signUp(){\r\n");
      out.write("\t\tlocation.href = \"signUp\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("  // Add smooth scrolling to all links in navbar + footer link\r\n");
      out.write("  $(\".navbar a, footer a[href='#myPage']\").on('click', function(event) {\r\n");
      out.write("    // Make sure this.hash has a value before overriding default behavior\r\n");
      out.write("    if (this.hash !== \"\") {\r\n");
      out.write("      // Prevent default anchor click behavior\r\n");
      out.write("      event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("      // Store hash\r\n");
      out.write("      var hash = this.hash;\r\n");
      out.write("\r\n");
      out.write("      // Using jQuery's animate() method to add smooth page scroll\r\n");
      out.write("      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area\r\n");
      out.write("      $('html, body').animate({\r\n");
      out.write("        scrollTop: $(hash).offset().top\r\n");
      out.write("      }, 900, function(){\r\n");
      out.write("   \r\n");
      out.write("        // Add hash (#) to URL when done scrolling (default click behavior)\r\n");
      out.write("        window.location.hash = hash;\r\n");
      out.write("      });\r\n");
      out.write("    } // End if\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  $(window).scroll(function() {\r\n");
      out.write("    $(\".slideanim\").each(function(){\r\n");
      out.write("      var pos = $(this).offset().top;\r\n");
      out.write("\r\n");
      out.write("      var winTop = $(window).scrollTop();\r\n");
      out.write("        if (pos < winTop + 600) {\r\n");
      out.write("          $(this).addClass(\"slide\");\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/index.jsp(217,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${who == 'anon'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t<li><a href=\"#\" onclick=\"login()\">LOGIN</a></li>\r\n");
          out.write("\t\t\t\t<li><a href=\"#\" onclick=\"signUp()\">SIGNUP</a></li>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<li><a href=\"#\" onclick=\"logout()\">LOGOUT</a></li>\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
