/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2020-05-28 18:09:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class vehicleProposal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1589781679034L));
    _jspx_dependants.put("jar:file:/D:/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/InsuranceSystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>보험상품 개발</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   function duplicationInsuranceName() {\r\n");
      out.write("      //보험상품 이름의 중복확인\r\n");
      out.write("\t\tvar propForm = document.getElementById('vehicleProposal')\r\n");
      out.write("\t\tpropForm.action = \"duplicationProposalName\"\r\n");
      out.write("\t\tpropForm.submit()\r\n");
      out.write("// \t\tif(duplication) {alert('이미 존재하는 이름입니다.');}\r\n");
      out.write("// \t\telse {alert('사용 가능한 이름입니다.');}\r\n");
      out.write("   }\r\n");
      out.write("   function tempSave() {\r\n");
      out.write("      alert('임시저장되었습니다.');\r\n");
      out.write("      var propForm = document.getElementById('vehicleProposal')\r\n");
      out.write("      propForm.action = \"tempSave\"\r\n");
      out.write("      propForm.submit()\r\n");
      out.write("   }\r\n");
      out.write("   function submitProposal() {\r\n");
      out.write("      alert('제안서 작성이 완료되었습니다.');\r\n");
      out.write("      var propForm = document.getElementById('vehicleProposal')\r\n");
      out.write("      propForm.action = \"writeProposal\"\r\n");
      out.write("      propForm.submit()\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <form action=\"writeVehicleProposal\" id=\"vehicleProposal\" method=\"post\">\r\n");
      out.write("      <table>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("               <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n");
      out.write("                  <tr style=\"background: url('img/table_mid.gif') repeat-x; text-align: center;\">\r\n");
      out.write("                     <td width=\"5\">\r\n");
      out.write("                        <img src=\"img/table_left.gif\" width=\"5\" height=\"30\" />\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>글쓰기</td>\r\n");
      out.write("                     <td width=\"5\">\r\n");
      out.write("                        <img src=\"img/table_right.gif\" width=\"5\" height=\"30\" />\r\n");
      out.write("                     </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <table>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">보험상품 이름</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"proposalName\" id = \"insuranceName\" size=\"50\" maxlength=\"100\"> <input type=\"button\" value=\"중복확인\" onclick=\"duplicationInsuranceName()\"> <input type=\"hidden\" name=\"insuranceNameDuplication\" value=\"nameUncheck\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">업무용 차량에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"forBusinessRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">자가용 차량에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"ownVehicleRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">렌탈 차량에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"rentalRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">SUV차량에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"suvRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">세단 차량에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"sedanRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">트럭 차량에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"truckRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">픽업차량에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"pickupTruckRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">버스차량에 대한 위험률</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input name=\"busRate\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">서류</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input type=file name=\"verificationDocuments\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td align=\"center\">기타사항</td>\r\n");
      out.write("                     <td>\r\n");
      out.write("                     \t<input name=\"proposalContent\" size=\"50\" maxlength=\"50\">\r\n");
      out.write("                     </td>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#dddddd\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("                  <tr height=\"1\" bgcolor=\"#82B5DF\">\r\n");
      out.write("                     <td colspan=\"4\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr align=\"center\">\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                     <td colspan=\"2\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"whichProposal\" value=\"vehicle\">\r\n");
      out.write("                        <button onclick=\"javascript:tempSave()\">임시저장</button>\r\n");
      out.write("                        <button onclick=\"javascript:submitProposal()\">제안서 제출</button>\r\n");
      out.write("                     <td>&nbsp;</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("               </table>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("   </form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
